id = "http-client"
name = "HTTP Client"
version = "0.1.3"
schema_version = 1
authors = ["hainet50b <contact@programacho.com>"]
description = "Highlights .http files and runs requests via a gutter run button. See the GitHub page for setup and feature demos."
repository = "https://github.com/hainet50b/zed-http-client"

[grammars.http]
repository = "https://github.com/rest-nvim/tree-sitter-http"
rev = "db8b4398de90b6d0b6c780aba96aaa2cd8e9202c"

[grammars.xml]
repository = "https://github.com/tree-sitter-grammars/tree-sitter-xml"
rev = "5000ae8f22d11fbe93939b05c1e37cf21117162d"
path = "xml"
