@baseUrl = https://httpbin.org/anything
@userId = 42

### Get all users
GET {{baseUrl}}/users
Accept: application/json

### Create a new user
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "hainet50b"
}

### Create a new user (XML)
POST {{baseUrl}}/users
Content-Type: application/xml

<user>
  <name>hainet50b</name>
</user>

### Create a new user (from file)
POST {{baseUrl}}/users
Content-Type: application/json

< ./payloads/new-user.json

### Create a new user (from templated file)
POST {{baseUrl}}/users
Content-Type: application/json

< ./payloads/templated-user.json

### Update a user
PUT {{baseUrl}}/users/{{userId}}
Content-Type: application/json

{
  "name": "programacho.com"
}

### Delete a user
DELETE {{baseUrl}}/users/{{userId}}

### Send a plain text note
POST {{baseUrl}}/notes
Content-Type: text/plain

Hello from Zed HTTP Client.

### Fetch a minified JSON response
GET https://catfact.ninja/fact
Accept: application/json

### Fetch a sample XML document
GET https://httpbin.org/xml
Accept: application/xml
